# Generated by Django 5.1.3 on 2024-11-13 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('cantidad_Actores', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sistema_votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(null=True)),
                ('comentario', models.CharField(max_length=100)),
                ('fechaHora', models.DateTimeField()),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Peliculas.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Peliculas.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='pelicula',
            name='usuario',
            field=models.ManyToManyField(through='Peliculas.Sistema_votacion', to='Peliculas.usuario'),
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_Cuenta', models.CharField(max_length=100)),
                ('banco', models.CharField(choices=[('CAIXA', 'CAIXA'), ('BBVA', 'BBVA'), ('UNICAJA', 'UNICAJA'), ('ING', 'ING')], max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CuentaBancaria_Usuario', to='Peliculas.usuario')),
            ],
        ),
    ]
